### ISSUE TITLE
不支持 中文 以外的目标语言翻译

### ISSUE THREAD

**Issue by intellism** [DarkCWK/youdao#1]
![image](https://user-images.githubusercontent.com/442894/188568364-4e4be5a9-bb4d-4749-96a3-44eeefd8e48b.png)

建议可以读取下配置，支持多种目标语言。

**Comment by DarkCWK** [comment]
好, 我尝试一下

**Comment by DarkCWK** [comment]
目前使用的 api 只支持 英, 日, 韩, 日后可能会重新找个 api 吧

**Comment by DarkCWK** [comment]
现在支持多个语种了, 不过 Comment Translate 本身支持很多语种, 而有道支持的语种有限, 所以不是所有语种都支持的
